name: decimal_type
description: A Decimal type for your Dart and Flutter projects.
version: 0.0.2
repository: https://github.com/maxbritto/decimal_type

environment:
  sdk: ^3.5.4

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
